### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by eastskyK** [wikibook/python-real-estate#1]
2.1 결국 가격이다 (개정)
row_num = sheet.range(1,1).end('down').end('down').end('down').row  
==>
row_num = sheet.range((1,1)).end('down').end('down').end('down').row

**Comment by wikibook** [comment]
안녕하세요. 위키북스 담당자입니다. 알려주신 사항을 저자분께 문의 드렸습니다.

결론적으로 윈도우 환경에서는 ( )가 없어도 문제가 없는데 맥 환경에서는 ( )를 추가해야 합니다. 다만  ( )를 추가해도 윈도우 환경에서도 잘 작동하므로 소스코드에 ( )를 추가하신다고 합니다.

참고 부탁드립니다. 고맙습니다.
